integrate Lighthouse into Github actions workflow

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -55,4 +55,4 @@ jobs:
       - name: Install the Lighthouse CI CLI.
         run: npm install -g @lhci/cli
       - name: Run 
-        run: lhci autorun --config=./lighthouserc-ci.js || echo "LHCI failed!"
+        run: lhci autorun --config=./lighthouserc.js || echo "LHCI failed!"
